version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invoice-backend
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: invoice-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BACKEND_HOST: http://localhost:8000
